title:       Sreya Vadapalli
tagline:     Biomedical Data Scientist & Public Health Researcher
email:       vadapalli.sreya98@gmail.com
github_user: SreyaVadapalli
linkedin_user: sreyavadapalli
cv_path:     /assets/files/Vadapalli_Sreya_Resume.pdf 

description:  Biomedical Data Scientist & Public Health Researcher.

markdown: kramdown
permalink: pretty
