title:       Sreya Vadapalli
tagline:     Health Data Scientist & Public Health Researcher
email:       sreya.vadapalli98@gmail.com
github_user: SreyaVadapalli
cv_path:     /assets/files/CV.pdf
description:  Health Data Scientist & Public Health Researcher. Interests in X, Y, and Z.

# --- Leave the settings below as they are ---
markdown: kramdown
permalink: pretty
